version: '3'
services:
  api:
    build:
      context: ./todoproject
      dockerfile: Dockerfile
    command: gunicorn todoproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/todoproject/staticfiles/
      - media_volume:/todoproject/mediafiles/
    expose:
      - 80
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - static_volume:/todoproject/staticfiles/
      - media_volume:/todoproject/mediafiles/
volumes:
  static_volume:
  media_volume:
