version: '3'
services:
  api:
    build:
      context: ./todoproject
      dockerfile: Dockerfile
      cache_from:
        - '${DJANGO_TUTORIAL_API_IMAGE}'
    image: '${DJANGO_TUTORIAL_API_IMAGE}'
    command: gunicorn todoproject.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 80
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    cache_from:
      - '${DJANGO_TUTORIAL_NGINX_IMAGE}'
    image: '${DJANGO_TUTORIAL_NGINX_IMAGE}'
    ports:
      - 80:80
